const CustomError = require("../extensions/custom-error");

module.exports = function transform(array) {
  
  try {
    
  } catch (error) {
    
  }

};
